include: package:flutter_lints/flutter.yaml


linter:
  rules:
        use_key_in_widget_constructors: false
        avoid_renaming_method_parameters: false
        use_build_context_synchronously: false
        prefer_const_constructors : false

