import 'package:flutter/material.dart';

const Color primaryColor = const Color.fromRGBO(135, 31, 255, 1);
const Color secondaryColor = const Color.fromRGBO(31, 33, 51, 1);
const Color walletCardColor = const Color.fromRGBO(43, 43, 75, 1);
const Color iconBackgroundColor = const Color.fromRGBO(83, 74, 223, 1);
final Color white = Colors.white;
final Color grey = Colors.grey;
final Color green = Colors.green;
final Color yellow = Colors.yellow;
final Color white38 = Colors.white38;
final Color white54 = Colors.white54;
final Color black = Colors.black;
const Color priceColor = const Color(0xFF0da88b);
const Color sellOrders = const Color(0xFF472a4a);
const Color sellPrice = const Color(0xFFe2103c);
const Color buyOrders = const Color(0xFF264559);
const Color buyPrice = const Color(0xFF0da88b);
final Color red = Colors.red;
const Color exgLogoColor = const Color.fromRGBO(207, 101, 68, .85);
const Color fabLogoColor = const Color.fromRGBO(162, 48, 203, .85);
